Update go.yml

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -1,31 +1,58 @@
+# This workflow will build a golang project
+# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
+
 name: Go
+
+env:
+  GIN_MODE: release
 
 on:
   push:
-    branches: [main]
+    branches: [ "main" ]
   pull_request:
-    branches: [main]
+    branches: [ "main" ]
+  workflow_dispatch:
 
 jobs:
   build:
     runs-on: ubuntu-latest
 
+    permissions:
+      checks: write
+
     steps:
-      - uses: actions/checkout@v3
+    - uses: actions/checkout@v3
 
-      - name: Set up Go 1.21
-        uses: actions/setup-go@v3
-        with:
-          go-version: '1.21'
-          cache: true
+    - name: Set up Go
+      uses: actions/setup-go@v3
+      with:
+        go-version-file: 'go.mod'
+        cache: true
 
-      - name: Check Go version
-        run: go version
+    - name: Revive Action
+      uses: morphy2k/revive-action@v2.4.1
 
-      - name: Prepare dependencies
-        run: |
-          go mod tidy
-          go mod download
+    #- name: Staticcheck
+     # uses: dominikh/staticcheck-action@v1.3.0
+    - name: Install staticcheck
+      run: go install honnef.co/go/tools/cmd/staticcheck@latest
 
-      - name: Staticcheck
-        uses: dominikh/staticcheck-action@v1.3.0
+    - name: Run staticcheck
+      run: staticcheck ./...
+      
+    - name: Build
+      run: |
+        go mod download
+        go install gotest.tools/gotestsum@latest
+
+    - name: Test
+      run: |
+        gotestsum --format=standard-verbose --junitfile=junit.xml
+
+    - name: Publish Test Report
+      uses: mikepenz/action-junit-report@v3
+      if: success() || failure() # always run even if the previous step fails
+      with:
+        report_paths: '**/junit.xml'
+        detailed_summary: true
+        include_passed: true
